hash-format = "sha256"

[[files]]
file = "config/DistantHorizons.toml"

[[files]]
file = "config/fancymenu/customizablemenus.txt"

[[files]]
file = "config/fancymenu/customization/main_menu.txt"

[[files]]
file = "config/fancymenu/customization/pause_menu.txt"

[[files]]
file = "config/fancymenu/options.txt"

[[files]]
file = "mods/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "options.txt"
preserve = true

[[files]]
file = "resourcepacks/unlustig.net/assets/minecraft/texts/splashes.txt"

[[files]]
file = "resourcepacks/unlustig.net/assets/minecraft/textures/gui/title/edition.png"

[[files]]
file = "resourcepacks/unlustig.net/assets/minecraft/textures/gui/title/minecraft.png"

[[files]]
file = "resourcepacks/unlustig.net/pack.mcmeta"

[[files]]
file = "resourcepacks/unlustig.net/pack.png"

[[files]]
file = "servers.dat"
preserve = true
