hash-format = "sha256"

[[files]]
file = "config/DistantHorizons.toml"

[[files]]
file = "mods/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "options.txt"
preserve = true

[[files]]
file = "resourcepacks/unlustig.net.zip"

[[files]]
file = "servers.dat"
preserve = true
