[client.advanced.autoUpdater]
	enableAutoUpdater = false

[common.logging.warning]
	showHighVanillaRenderDistanceWarning = false
	showGarbageCollectorWarning = false
	logGarbageCollectorWarning = false
